# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/touches.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/touches.proto',
  package='touches',
  syntax='proto3',
  serialized_pb=_b('\n\x16protobuf/touches.proto\x12\x07touches\"\x1e\n\x06Vector\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"O\n\x06Sample\x12\x0c\n\x04time\x18\x01 \x01(\x01\x12!\n\x08position\x18\x02 \x01(\x0b\x32\x0f.touches.Vector\x12\x14\n\x0cmajor_radius\x18\x03 \x01(\x01\"*\n\x06Stroke\x12 \n\x07samples\x18\x01 \x03(\x0b\x32\x0f.touches.Sample\"+\n\x07\x44rawing\x12 \n\x07strokes\x18\x01 \x03(\x0b\x32\x0f.touches.Stroke\"1\n\x0b\x44rawingList\x12\"\n\x08\x64rawings\x18\x01 \x03(\x0b\x32\x10.touches.Drawing\"W\n\nRawDataSet\x12)\n\x0b\x64rawingList\x18\x01 \x01(\x0b\x32\x14.touches.DrawingList\x12\x1e\n\x06labels\x18\x02 \x03(\x0e\x32\x0e.touches.Label\"6\n\x05Image\x12\x0e\n\x06height\x18\x01 \x01(\x05\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06values\x18\x0f \x01(\x0c\"M\n\rLabelledImage\x12\x1d\n\x05image\x18\x01 \x01(\x0b\x32\x0e.touches.Image\x12\x1d\n\x05label\x18\x02 \x01(\x0e\x32\x0e.touches.Label\"=\n\x0bTrainingSet\x12.\n\x0elabelledImages\x18\x01 \x03(\x0b\x32\x16.touches.LabelledImage\"+\n\tImageList\x12\x1e\n\x06images\x18\x01 \x03(\x0b\x32\x0e.touches.Image*\xeb\x01\n\x05Label\x12\t\n\x05OTHER\x10\x00\x12\r\n\tCHECKMARK\x10\x01\x12\t\n\x05XMARK\x10\x02\x12\x12\n\x0eLINE_ASCENDING\x10\x12\x12\x0c\n\x08SCRIBBLE\x10\x17\x12\n\n\x06\x43IRCLE\x10\x18\x12\x16\n\x12SEMICIRCLE_OPEN_UP\x10\x1e\x12\t\n\x05HEART\x10\'\x12\r\n\tPLUS_SIGN\x10(\x12\x11\n\rQUESTION_MARK\x10\x32\x12\x14\n\x10LETTER_A_CAPITAL\x10<\x12\x14\n\x10LETTER_B_CAPITAL\x10=\x12\x0f\n\nFACE_HAPPY\x10\x82\x01\x12\r\n\x08\x46\x41\x43\x45_SAD\x10\x83\x01\x62\x06proto3')
)

_LABEL = _descriptor.EnumDescriptor(
  name='Label',
  full_name='touches.Label',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OTHER', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHECKMARK', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XMARK', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LINE_ASCENDING', index=3, number=18,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SCRIBBLE', index=4, number=23,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CIRCLE', index=5, number=24,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEMICIRCLE_OPEN_UP', index=6, number=30,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEART', index=7, number=39,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLUS_SIGN', index=8, number=40,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUESTION_MARK', index=9, number=50,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LETTER_A_CAPITAL', index=10, number=60,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LETTER_B_CAPITAL', index=11, number=61,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FACE_HAPPY', index=12, number=130,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FACE_SAD', index=13, number=131,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=621,
  serialized_end=856,
)
_sym_db.RegisterEnumDescriptor(_LABEL)

Label = enum_type_wrapper.EnumTypeWrapper(_LABEL)
OTHER = 0
CHECKMARK = 1
XMARK = 2
LINE_ASCENDING = 18
SCRIBBLE = 23
CIRCLE = 24
SEMICIRCLE_OPEN_UP = 30
HEART = 39
PLUS_SIGN = 40
QUESTION_MARK = 50
LETTER_A_CAPITAL = 60
LETTER_B_CAPITAL = 61
FACE_HAPPY = 130
FACE_SAD = 131



_VECTOR = _descriptor.Descriptor(
  name='Vector',
  full_name='touches.Vector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='touches.Vector.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='touches.Vector.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=65,
)


_SAMPLE = _descriptor.Descriptor(
  name='Sample',
  full_name='touches.Sample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='touches.Sample.time', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='touches.Sample.position', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='major_radius', full_name='touches.Sample.major_radius', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=146,
)


_STROKE = _descriptor.Descriptor(
  name='Stroke',
  full_name='touches.Stroke',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='samples', full_name='touches.Stroke.samples', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=190,
)


_DRAWING = _descriptor.Descriptor(
  name='Drawing',
  full_name='touches.Drawing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='strokes', full_name='touches.Drawing.strokes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=235,
)


_DRAWINGLIST = _descriptor.Descriptor(
  name='DrawingList',
  full_name='touches.DrawingList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='drawings', full_name='touches.DrawingList.drawings', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=286,
)


_RAWDATASET = _descriptor.Descriptor(
  name='RawDataSet',
  full_name='touches.RawDataSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='drawingList', full_name='touches.RawDataSet.drawingList', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='labels', full_name='touches.RawDataSet.labels', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=375,
)


_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='touches.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='touches.Image.height', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='touches.Image.width', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='values', full_name='touches.Image.values', index=2,
      number=15, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=377,
  serialized_end=431,
)


_LABELLEDIMAGE = _descriptor.Descriptor(
  name='LabelledImage',
  full_name='touches.LabelledImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='touches.LabelledImage.image', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='label', full_name='touches.LabelledImage.label', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=433,
  serialized_end=510,
)


_TRAININGSET = _descriptor.Descriptor(
  name='TrainingSet',
  full_name='touches.TrainingSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='labelledImages', full_name='touches.TrainingSet.labelledImages', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=512,
  serialized_end=573,
)


_IMAGELIST = _descriptor.Descriptor(
  name='ImageList',
  full_name='touches.ImageList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='images', full_name='touches.ImageList.images', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=575,
  serialized_end=618,
)

_SAMPLE.fields_by_name['position'].message_type = _VECTOR
_STROKE.fields_by_name['samples'].message_type = _SAMPLE
_DRAWING.fields_by_name['strokes'].message_type = _STROKE
_DRAWINGLIST.fields_by_name['drawings'].message_type = _DRAWING
_RAWDATASET.fields_by_name['drawingList'].message_type = _DRAWINGLIST
_RAWDATASET.fields_by_name['labels'].enum_type = _LABEL
_LABELLEDIMAGE.fields_by_name['image'].message_type = _IMAGE
_LABELLEDIMAGE.fields_by_name['label'].enum_type = _LABEL
_TRAININGSET.fields_by_name['labelledImages'].message_type = _LABELLEDIMAGE
_IMAGELIST.fields_by_name['images'].message_type = _IMAGE
DESCRIPTOR.message_types_by_name['Vector'] = _VECTOR
DESCRIPTOR.message_types_by_name['Sample'] = _SAMPLE
DESCRIPTOR.message_types_by_name['Stroke'] = _STROKE
DESCRIPTOR.message_types_by_name['Drawing'] = _DRAWING
DESCRIPTOR.message_types_by_name['DrawingList'] = _DRAWINGLIST
DESCRIPTOR.message_types_by_name['RawDataSet'] = _RAWDATASET
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['LabelledImage'] = _LABELLEDIMAGE
DESCRIPTOR.message_types_by_name['TrainingSet'] = _TRAININGSET
DESCRIPTOR.message_types_by_name['ImageList'] = _IMAGELIST
DESCRIPTOR.enum_types_by_name['Label'] = _LABEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vector = _reflection.GeneratedProtocolMessageType('Vector', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR,
  __module__ = 'protobuf.touches_pb2'
  # @@protoc_insertion_point(class_scope:touches.Vector)
  ))
_sym_db.RegisterMessage(Vector)

Sample = _reflection.GeneratedProtocolMessageType('Sample', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLE,
  __module__ = 'protobuf.touches_pb2'
  # @@protoc_insertion_point(class_scope:touches.Sample)
  ))
_sym_db.RegisterMessage(Sample)

Stroke = _reflection.GeneratedProtocolMessageType('Stroke', (_message.Message,), dict(
  DESCRIPTOR = _STROKE,
  __module__ = 'protobuf.touches_pb2'
  # @@protoc_insertion_point(class_scope:touches.Stroke)
  ))
_sym_db.RegisterMessage(Stroke)

Drawing = _reflection.GeneratedProtocolMessageType('Drawing', (_message.Message,), dict(
  DESCRIPTOR = _DRAWING,
  __module__ = 'protobuf.touches_pb2'
  # @@protoc_insertion_point(class_scope:touches.Drawing)
  ))
_sym_db.RegisterMessage(Drawing)

DrawingList = _reflection.GeneratedProtocolMessageType('DrawingList', (_message.Message,), dict(
  DESCRIPTOR = _DRAWINGLIST,
  __module__ = 'protobuf.touches_pb2'
  # @@protoc_insertion_point(class_scope:touches.DrawingList)
  ))
_sym_db.RegisterMessage(DrawingList)

RawDataSet = _reflection.GeneratedProtocolMessageType('RawDataSet', (_message.Message,), dict(
  DESCRIPTOR = _RAWDATASET,
  __module__ = 'protobuf.touches_pb2'
  # @@protoc_insertion_point(class_scope:touches.RawDataSet)
  ))
_sym_db.RegisterMessage(RawDataSet)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE,
  __module__ = 'protobuf.touches_pb2'
  # @@protoc_insertion_point(class_scope:touches.Image)
  ))
_sym_db.RegisterMessage(Image)

LabelledImage = _reflection.GeneratedProtocolMessageType('LabelledImage', (_message.Message,), dict(
  DESCRIPTOR = _LABELLEDIMAGE,
  __module__ = 'protobuf.touches_pb2'
  # @@protoc_insertion_point(class_scope:touches.LabelledImage)
  ))
_sym_db.RegisterMessage(LabelledImage)

TrainingSet = _reflection.GeneratedProtocolMessageType('TrainingSet', (_message.Message,), dict(
  DESCRIPTOR = _TRAININGSET,
  __module__ = 'protobuf.touches_pb2'
  # @@protoc_insertion_point(class_scope:touches.TrainingSet)
  ))
_sym_db.RegisterMessage(TrainingSet)

ImageList = _reflection.GeneratedProtocolMessageType('ImageList', (_message.Message,), dict(
  DESCRIPTOR = _IMAGELIST,
  __module__ = 'protobuf.touches_pb2'
  # @@protoc_insertion_point(class_scope:touches.ImageList)
  ))
_sym_db.RegisterMessage(ImageList)


# @@protoc_insertion_point(module_scope)
